#!/usr/bin/perl
# Convert BerkeleyDB File into Recno
# http://search.cpan.org/~pmqs/BerkeleyDB-0.39/BerkeleyDB.pod
#------------------------------------------------------------------------------#
use strict;
use warnings;
use BerkeleyDB;
use vars qw( @array $counter );
$| = 1;

#------------------------------------------------------------------------------#
my $filename = "links-general.csv";
my $database = "parts/links";

#------------------------------------------------------------------------------#
$counter   = 0;
&load_data($filename);
my $number = $counter; $number =~ s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
print "Total=" . $number . "\n";
untie @array;

#------------------------------------------------------------------------------#
sub load_data {

my $urlBan = qr/(gizmine|bogg\.com|healthcare\.com|houzz\.com|
    yellowpages|google|advert|realestate|game|feed|porn|store|inventory|vehicles|job|
    username|manufact|walmart|torrent|download|upload|search|click|hotel|classified|CFTOKEN|events|
    finance|lesbian|pgid\=|jsessionid|login|islam|amazon|yelp|bit\.ly|tripadvisor|amazon|comprods|
    remodeling|halloween|china|football|section\.php|sitemap|product)/;

    my $partition = 0;
    my $sourcefile = shift;
    open(FILE, $sourcefile) or die "$!";

    open(OUT, '>', $database . "." . $partition);

    while (<FILE>)
    {
       if($_ !~ /$urlBan/ix ) {
            my $line = $_;
            chomp($line);

            # chop($line);
            # my @fields = split '","' , $line;
            my @fields = split("\t", $line);

            my $number = $counter; $number =~ s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
            print "$number : " . $fields[1] . "\n" if (($counter % 100000) == 0);
            print OUT $fields[1] . "\n" if exists $fields[1] ;

            $counter++;
            if($counter > 500_000_000) {
                close(OUT);
                $partition++;
                open(OUT, '>', $database . "." . $partition);
                $counter=0;
            }
        }
    }

    close(OUT);
    close(FILE);
}

#------------------------------------------------------------------------------#
__END__
open(my $fh, '>', 'report.txt');
print $fh "My first report generated by perl\n";
close $fh;
print "done\n";
